services:
  app:
    build: ./dev/
    volumes:
      - .:/usr/src/app
      - ruby_bundles:/usr/local/bundle
    environment:
      - RAILS_ENV=development
      - DB_HOST=db
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    depends_on:
      - db
    ports:
      - "3000:3000"
    networks:
      - app_net
  db:
    image: postgres:16.4-alpine3.20
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    networks:
      - app_net
networks:
  app_net:
volumes:
  ruby_bundles:
  db_data: